language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

global:
  - BUILD_DOCS=false
  - SUBMIT_CODECOV=false
  - FLAKE_8=false

jobs:
  fast_finish: true
  include:
    - python: 3.8  # This build will run only 'flake8'
      env: FLAKE_8=true
    - python: 3.7
      env: QT="pyqt5cf"
    - python: 3.7
      env: QT="pyside2"
    - python: 3.8
      env: QT="pyqt5cf" BUILD_DOCS=true SUBMIT_CODECOV=true
    - python: 3.8
      env: QT="pyside2"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.7 QT="pyqt5cf"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.7 QT="pyside2"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.8 QT="pyqt5cf"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.8 QT="pyside2"
    - python: 3.7
      env: QT="pyqt5"
    - python: 3.8
      env: QT="pyqt5"
  allow_failures:
    - python: 3.7
      env: QT="pyside2"
    - python: 3.8
      env: QT="pyside2"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.7 QT="pyside2"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.8 QT="pyside2"

before_install:
  - if [ $FLAKE_8 == 'true' ]; then
      pip install flake8;
      flake8 .;
      let res=$?;
      echo "The project code was verified with 'flake8'. Exit code ($res).";
      exit $res;
    fi
  - |
    set -e
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      # Install 'herbstluftwm' (on Linux only)
      sudo apt-get update
      sudo apt-get install -y xvfb herbstluftwm
    fi
  - |
    set -e
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        arch="Linux"
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
        arch="MacOSX"
    else
        echo "Unknown arch $TRAVIS_OS_NAME"
        exit 1
    fi
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-${arch}-x86_64.sh -O miniconda.sh
    chmod +x miniconda.sh
    ./miniconda.sh -b -p ~/mc
    source ~/mc/etc/profile.d/conda.sh
    conda update conda --yes
    export CONDARC=ci/condarc

install:

  - |
    set -e
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      # Run 'xvfb' (on Linux only)
      export DISPLAY=:99.0
      sudo /sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset
      sleep 3
    fi
  - conda create -y -n testenv python=$TRAVIS_PYTHON_VERSION
  - conda activate testenv
  - |
    set -e
    if [ $QT == "pyside2" ]; then
      conda install -y pyside2 -c conda-forge;
      conda update -y pyside2 -c conda-forge
    elif [ $QT == "pyqt5" ]; then
      conda install -y pyqt;
      conda update -y pyqt
    elif [ $QT == "pyqt5cf" ]; then
      conda install -y pyqt -c conda-forge;
      conda update -y pyqt -c conda-forge
    else
        echo "Unknown Qt package $QT"
        exit 1
    fi
  - pip install --upgrade pip setuptools numpy
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .
  - conda list
  - pip list

before_script:
  - |
    set -e
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      # Run 'herbstluftwm' (on Linux only)
      herbstluftwm &
      sleep 1
    fi

script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m -i  # Generate test coverage report.
  - |
    set -e
    if [ $BUILD_DOCS == 'true' ]; then
      make -C docs html  # Build the documentation.
      # Disable Jekyll theme
      touch docs/build/html/.nojekyll
    fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: "docs/build/html"
  on:
    branch: master
    # The following conditions guarantees that the docs will be deployed only if the build
    #   is run in the main repository (this may easily changed)
    condition: $BUILD_DOCS == true && $TRAVIS_REPO_SLUG == "bluesky/bluesky-widgets"

after_success:
  - if [ $SUBMIT_CODECOV == 'true' ]; then codecov; fi;
